import { Metadata } from "next";
import NotFound from "../not-found";

export const metadata: Metadata = {
  title: "Not Found!",
  description: "Generated by create next app",
  icons: {
    icon: "/images/anisage-fav.png",
  },
  robots: {
    index: false,
    follow: false,
  },
};
export default NotFound;
