import Contact from "@/features/contact";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact - AniSage",
  description: "Generated by create next app",
  icons: {
    icon: "/images/anisage-fav.png",
  },
  robots: {
    index: false,
    follow: false,
  },
};
export default Contact;
