import PrivacyPolicy from "@/features/privacy-policy";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - AniSage",
  description: "Generated by create next app",
  icons: {
    icon: "/images/anisage-fav.png",
  },
  robots: {
    index: false,
    follow: false,
  },
};
export default PrivacyPolicy;
