import ForgotPass from "@/features/forgot-pass";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Forgot Password - AniSage",
  description: "Generated by create next app",
  icons: {
    icon: "/images/anisage-fav.png",
  },
  robots: {
    index: false,
    follow: false,
  },
};
export default ForgotPass;
